changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
  categories:
    - title: ğŸš¨ Breaking Changes
      labels:
        - breaking-change
    - title: âœ¨ New Features
      labels:
        - enhancement
    - title: ğŸ› Bug Fixes
      labels:
        - bug
